package com.mpe.common.dashboard;

public enum DashboardType {

	TRADE_IN_APPROVAL,
	CANCEL_SALES,
	CANCEL_WO,
	CANCEL_ADD,
	CANCEL_REKLAS,
	EDIT_ADD,
	EDIT_REKLAS,
	APPROVAL,
	APPROVAL_CANCEL_OTHER_CHARGES,
	APPROVAL_CANCEL,
	APPROVAL_CANCEL_TERMINATION_PENALTY,
	APPROVAL_DEBET_KL,
	APPROVAL_UNIT_TITIPAN_NASABAH,
	APPROVAL_REFINANCE_TERMINATION,
	APPROVAL_RESET_PASSWORD,
	APPROVAL_REKLAS,
	APPROVAL_CREATE
}
